### ISSUE TITLE
adjust repo structure to MAGIC requirements

### ISSUE THREAD

**Issue by dneise** [fact-project/weather_station#6]
Since some time, the RG11 sensors are running on the MAGIC site, and a python based readout script is running on the MAGIC "ATCA" PC. 

I would like this repo to be structured in a way, so Auni can just `git clone` this repo to that PC, so it makes sense there. 

I like however this combination of:

* hardware description in the `docs/` folder
* readout software
* arduino-firmware

all in one repo.

The folder on the ATCA PC, will be called `rain_sensor` since MAGIC has already a weather station and so this folder name is out of the question. 

So I propose a folder structure, similar to this:

```
rain_sensor/
    README.md
    rain_sensor.py
    docs/
        schematics/
        pictures/
        datasheets/
    arduino/
        src/
        .pioenvs/ethernet/
        platformio.ini
```

--- 

With this structure, Auni can clone it, and immediately call the `rain_sensor.py`. 
The output of the rain_sensor.py is basically one folder, containing daily json-lines-files, with one line per second **and** a since file, typically named `current.json`, which can be used for the website. 

The location of the output can be freely chosen, but it would fit into this folder structure e.g. like this:
```
rain_sensor/
    README.md
    rain_sensor.py
    current.json
    daily_jsonl/
    ...
```

The question is, what should be done, with the documentation and code, developed for the complete FACT weather station? This is so nicely collected and should not be lost, I think. One possibility would be to open a new repo, just for the the rain sensors. Another would be to keep the current status in a branch or tag, so it does not get lost, and then simply restructure the current master according or similar to the upper proposal. 

@jebuss what do you think? New repo (we could simply fork from this, I guess) or tag the current state for later reference and basically hijack this repo for the rain_sensor only?

@asomero  do you like this folder structure?

**Comment by aunis** [comment]
@dneise I like it a lot.

**Comment by dneise** [comment]
moved this issue to https://github.com/fact-project/rain_sensor/issues/1
